[package]
name = "rust-basics"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.46.1", features = ["full"] }
thiserror = "2.0"
anyhow = "1.0"
colored = "2.1"
chrono = { version = "0.4", features = ["serde"] }